### ISSUE TITLE
Deploy 3.3.2.0 to maven

### ISSUE THREAD

**Issue by shooit** [clojurewerkz/ogre#102]
I see that there is a 3.3.2.0 tag but there is no Maven jar and the project.clj is still a snapshot. Are there more features that need work before this can be deployed?

**Comment by michaelklishin** [comment]
Unfortunately currently tagging and release are done by different people. I am not a fan of ahead-of-time tagging but I'm also responsible for not producing a release in a few weeks.

**Comment by spmallette** [comment]
I'm happy to coordinate it differently so that it doesn't create confusion if you like @michaelklishin ... maybe i should just create an issue here in Ogre that something is ready to release (maybe include the commit id in the description) and then you can be responsible for the release and the tag. how does that sound?

**Comment by michaelklishin** [comment]
@spmallette we should find a way to grant you access to the Clojars account so that you don't have to wait for me. Can you email me your username?

**Comment by spmallette** [comment]
I just sent you my username, but when i logged into clojars (which i never do), it looks like i'm already part of the clojurewerkz group? have i been able to deploy all this time or did you just do that?

**Comment by michaelklishin** [comment]
@spmallette hm, I must have missed the email but no, this is not a recent change. Try `lein deploy clojars`? ;)

**Comment by spmallette** [comment]
that worked - https://clojars.org/clojurewerkz/ogre/versions/3.3.2.0

i guess that streamlines the release process going forward. :smile:  i'll just give you a heads up around the times i deploy things.

**Comment by michaelklishin** [comment]
Hooray. @spmallette I wouldn't mind reviewing change logs so that we maintain and improve their quality.

**Comment by spmallette** [comment]
sure thing - i'll just DM when i'm thinking about a release. i'll give it a few days from that point before i pull the trigger to deploy/tag in case you have any feedback.
