### ISSUE TITLE
When I attempt to do require ogre core in my project namespace I get classnotfound issue

### ISSUE THREAD

**Issue by danielmartincraig** [clojurewerkz/ogre#110]
Hi, when I do 

(ns com.swacorp.bkrgraph-pdx-neptune-populator
  (:require  [clojurewerkz.ogre.core])
  (:gen-class))

I get the following error.

2. Unhandled clojure.lang.Compiler$CompilerException
   Error compiling clojurewerkz/ogre/core.clj at (183:5)
   #:clojure.error{:phase :compile-syntax-check,
                   :line 183,
                   :column 5,
                   :source "clojurewerkz/ogre/core.clj"}
             Compiler.java: 6812  clojure.lang.Compiler/analyze
             Compiler.java: 6749  clojure.lang.Compiler/analyze
             Compiler.java: 3827  clojure.lang.Compiler$InvokeExpr/parse
             Compiler.java: 7113  clojure.lang.Compiler/analyzeSeq
             Compiler.java: 6793  clojure.lang.Compiler/analyze
             Compiler.java: 6749  clojure.lang.Compiler/analyze
             Compiler.java: 2828  clojure.lang.Compiler$IfExpr$Parser/parse
             Compiler.java: 7111  clojure.lang.Compiler/analyzeSeq
             Compiler.java: 6793  clojure.lang.Compiler/analyze
             Compiler.java: 7099  clojure.lang.Compiler/analyzeSeq
             Compiler.java: 6793  clojure.lang.Compiler/analyze
             Compiler.java: 6749  clojure.lang.Compiler/analyze
             Compiler.java: 6124  clojure.lang.Compiler$BodyExpr$Parser/parse
             Compiler.java: 5471  clojure.lang.Compiler$FnMethod/parse
             Compiler.java: 4033  clojure.lang.Compiler$FnExpr/parse
             Compiler.java: 7109  clojure.lang.Compiler/analyzeSeq
             Compiler.java: 6793  clojure.lang.Compiler/analyze
             Compiler.java: 7099  clojure.lang.Compiler/analyzeSeq
             Compiler.java: 6793  clojure.lang.Compiler/analyze
             Compiler.java:   38  clojure.lang.Compiler/access$300
             Compiler.java:  596  clojure.lang.Compiler$DefExpr$Parser/parse
             Compiler.java: 7111  clojure.lang.Compiler/analyzeSeq
             Compiler.java: 6793  clojure.lang.Compiler/analyze
             Compiler.java: 6749  clojure.lang.Compiler/analyze
             Compiler.java: 7185  clojure.lang.Compiler/eval
             Compiler.java: 7640  clojure.lang.Compiler/load
                   RT.java:  381  clojure.lang.RT/loadResourceScript
                   RT.java:  372  clojure.lang.RT/loadResourceScript
                   RT.java:  459  clojure.lang.RT/load
                   RT.java:  424  clojure.lang.RT/load
                  core.clj: 6115  clojure.core/load/fn
                  core.clj: 6114  clojure.core/load
                  core.clj: 6098  clojure.core/load
               RestFn.java:  408  clojure.lang.RestFn/invoke
                  core.clj: 5897  clojure.core/load-one
                  core.clj: 5892  clojure.core/load-one
                  core.clj: 5937  clojure.core/load-lib/fn
                  core.clj: 5936  clojure.core/load-lib
                  core.clj: 5917  clojure.core/load-lib
               RestFn.java:  142  clojure.lang.RestFn/applyTo
                  core.clj:  669  clojure.core/apply
                  core.clj: 5974  clojure.core/load-libs
                  core.clj: 5958  clojure.core/load-libs
               RestFn.java:  137  clojure.lang.RestFn/applyTo
                  core.clj:  669  clojure.core/apply
                  core.clj: 5996  clojure.core/require
                  core.clj: 5996  clojure.core/require
               RestFn.java:  408  clojure.lang.RestFn/invoke
                      REPL:    1  com.swacorp.bkrgraph-pdx-neptune-populator/eval5314/loading--auto--
                      REPL:    1  com.swacorp.bkrgraph-pdx-neptune-populator/eval5314
                      REPL:    1  com.swacorp.bkrgraph-pdx-neptune-populator/eval5314
             Compiler.java: 7181  clojure.lang.Compiler/eval
             Compiler.java: 7170  clojure.lang.Compiler/eval
             Compiler.java: 7136  clojure.lang.Compiler/eval
                  core.clj: 3202  clojure.core/eval
                  core.clj: 3198  clojure.core/eval
    interruptible_eval.clj:   87  nrepl.middleware.interruptible-eval/evaluate/fn/fn
                  AFn.java:  152  clojure.lang.AFn/applyToHelper
                  AFn.java:  144  clojure.lang.AFn/applyTo
                  core.clj:  667  clojure.core/apply
                  core.clj: 1977  clojure.core/with-bindings*
                  core.clj: 1977  clojure.core/with-bindings*
               RestFn.java:  425  clojure.lang.RestFn/invoke
    interruptible_eval.clj:   87  nrepl.middleware.interruptible-eval/evaluate/fn
                  main.clj:  437  clojure.main/repl/read-eval-print/fn
                  main.clj:  437  clojure.main/repl/read-eval-print
                  main.clj:  458  clojure.main/repl/fn
                  main.clj:  458  clojure.main/repl
                  main.clj:  368  clojure.main/repl
               RestFn.java: 1523  clojure.lang.RestFn/invoke
    interruptible_eval.clj:   84  nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:   56  nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:  152  nrepl.middleware.interruptible-eval/interruptible-eval/fn/fn
                  AFn.java:   22  clojure.lang.AFn/run
               session.clj:  202  nrepl.middleware.session/session-exec/main-loop/fn
               session.clj:  201  nrepl.middleware.session/session-exec/main-loop
                  AFn.java:   22  clojure.lang.AFn/run
               Thread.java:  832  java.lang.Thread/run

1. Caused by java.lang.ClassNotFoundException
   org.apache.commons.configuration.Configuration

       URLClassLoader.java:  435  java.net.URLClassLoader/findClass
   DynamicClassLoader.java:   69  clojure.lang.DynamicClassLoader/findClass
          ClassLoader.java:  589  java.lang.ClassLoader/loadClass
   DynamicClassLoader.java:   77  clojure.lang.DynamicClassLoader/loadClass
          ClassLoader.java:  522  java.lang.ClassLoader/loadClass
                Class.java:   -2  java.lang.Class/forName0
                Class.java:  468  java.lang.Class/forName
                   RT.java: 2212  clojure.lang.RT/classForName
                   RT.java: 2221  clojure.lang.RT/classForName
             Compiler.java: 7399  clojure.lang.Compiler/resolveIn
             Compiler.java: 7362  clojure.lang.Compiler/resolve
             Compiler.java: 7323  clojure.lang.Compiler/analyzeSymbol
             Compiler.java: 6772  clojure.lang.Compiler/analyze
             Compiler.java: 6749  clojure.lang.Compiler/analyze
             Compiler.java: 3827  clojure.lang.Compiler$InvokeExpr/parse
             Compiler.java: 7113  clojure.lang.Compiler/analyzeSeq
             Compiler.java: 6793  clojure.lang.Compiler/analyze
             Compiler.java: 6749  clojure.lang.Compiler/analyze
             Compiler.java: 2828  clojure.lang.Compiler$IfExpr$Parser/parse
             Compiler.java: 7111  clojure.lang.Compiler/analyzeSeq
             Compiler.java: 6793  clojure.lang.Compiler/analyze
             Compiler.java: 7099  clojure.lang.Compiler/analyzeSeq
             Compiler.java: 6793  clojure.lang.Compiler/analyze
             Compiler.java: 6749  clojure.lang.Compiler/analyze
             Compiler.java: 6124  clojure.lang.Compiler$BodyExpr$Parser/parse
             Compiler.java: 5471  clojure.lang.Compiler$FnMethod/parse
             Compiler.java: 4033  clojure.lang.Compiler$FnExpr/parse
             Compiler.java: 7109  clojure.lang.Compiler/analyzeSeq
             Compiler.java: 6793  clojure.lang.Compiler/analyze
             Compiler.java: 7099  clojure.lang.Compiler/analyzeSeq
             Compiler.java: 6793  clojure.lang.Compiler/analyze
             Compiler.java:   38  clojure.lang.Compiler/access$300
             Compiler.java:  596  clojure.lang.Compiler$DefExpr$Parser/parse
             Compiler.java: 7111  clojure.lang.Compiler/analyzeSeq
             Compiler.java: 6793  clojure.lang.Compiler/analyze
             Compiler.java: 6749  clojure.lang.Compiler/analyze
             Compiler.java: 7185  clojure.lang.Compiler/eval
             Compiler.java: 7640  clojure.lang.Compiler/load
                   RT.java:  381  clojure.lang.RT/loadResourceScript
                   RT.java:  372  clojure.lang.RT/loadResourceScript
                   RT.java:  459  clojure.lang.RT/load
                   RT.java:  424  clojure.lang.RT/load
                  core.clj: 6115  clojure.core/load/fn
                  core.clj: 6114  clojure.core/load
                  core.clj: 6098  clojure.core/load
               RestFn.java:  408  clojure.lang.RestFn/invoke
                  core.clj: 5897  clojure.core/load-one
                  core.clj: 5892  clojure.core/load-one
                  core.clj: 5937  clojure.core/load-lib/fn
                  core.clj: 5936  clojure.core/load-lib
                  core.clj: 5917  clojure.core/load-lib
               RestFn.java:  142  clojure.lang.RestFn/applyTo
                  core.clj:  669  clojure.core/apply
                  core.clj: 5974  clojure.core/load-libs
                  core.clj: 5958  clojure.core/load-libs
               RestFn.java:  137  clojure.lang.RestFn/applyTo
                  core.clj:  669  clojure.core/apply
                  core.clj: 5996  clojure.core/require
                  core.clj: 5996  clojure.core/require
               RestFn.java:  408  clojure.lang.RestFn/invoke
                      REPL:    1  com.swacorp.bkrgraph-pdx-neptune-populator/eval5314/loading--auto--
                      REPL:    1  com.swacorp.bkrgraph-pdx-neptune-populator/eval5314
                      REPL:    1  com.swacorp.bkrgraph-pdx-neptune-populator/eval5314
             Compiler.java: 7181  clojure.lang.Compiler/eval
             Compiler.java: 7170  clojure.lang.Compiler/eval
             Compiler.java: 7136  clojure.lang.Compiler/eval
                  core.clj: 3202  clojure.core/eval
                  core.clj: 3198  clojure.core/eval
    interruptible_eval.clj:   87  nrepl.middleware.interruptible-eval/evaluate/fn/fn
                  AFn.java:  152  clojure.lang.AFn/applyToHelper
                  AFn.java:  144  clojure.lang.AFn/applyTo
                  core.clj:  667  clojure.core/apply
                  core.clj: 1977  clojure.core/with-bindings*
                  core.clj: 1977  clojure.core/with-bindings*
               RestFn.java:  425  clojure.lang.RestFn/invoke
    interruptible_eval.clj:   87  nrepl.middleware.interruptible-eval/evaluate/fn
                  main.clj:  437  clojure.main/repl/read-eval-print/fn
                  main.clj:  437  clojure.main/repl/read-eval-print
                  main.clj:  458  clojure.main/repl/fn
                  main.clj:  458  clojure.main/repl
                  main.clj:  368  clojure.main/repl
               RestFn.java: 1523  clojure.lang.RestFn/invoke
    interruptible_eval.clj:   84  nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:   56  nrepl.middleware.interruptible-eval/evaluate
    interruptible_eval.clj:  152  nrepl.middleware.interruptible-eval/interruptible-eval/fn/fn
                  AFn.java:   22  clojure.lang.AFn/run
               session.clj:  202  nrepl.middleware.session/session-exec/main-loop/fn
               session.clj:  201  nrepl.middleware.session/session-exec/main-loop
                  AFn.java:   22  clojure.lang.AFn/run
               Thread.java:  832  java.lang.Thread/run

and here is my deps.edn: 

{:paths ["src" "resources"]
 :deps {org.clojure/clojure {:mvn/version "1.10.3"}
        com.amazonaws/amazon-neptune-gremlin-java-sigv4 {:mvn/version "2.1.2"}
        org.apache.tinkerpop/gremlin-driver {:mvn/version "3.5.0"}
        clojurewerkz/ogre {:mvn/version "3.4.11.0"}
        org.apache.tinkerpop/tinkergraph-gremlin {:mvn/version "3.5.0"}
        org.apache.commons/commons-configuration2 {:mvn/version "2.7"}}
 :aliases
 {:run-m {:main-opts ["-m" "com.example"]}
  :run-x {:ns-default com.example
          :exec-fn greet
          :exec-args {:name "Clojure"}}
  :test {:extra-paths ["test"]
         :extra-deps {org.clojure/test.check {:mvn/version "1.1.0"}}}
  :runner
  {:extra-deps {com.cognitect/test-runner
                {:git/url "https://github.com/cognitect-labs/test-runner"
                 :sha "b6b3193fcc42659d7e46ecd1884a228993441182"}}
   :main-opts ["-m" "cognitect.test-runner"
               "-d" "test"]}
  :uberjar {:replace-deps {com.github.seancorfield/depstar {:mvn/version "2.0.211"}}
            :exec-fn hf.depstar/uberjar
            :exec-args {:aot true
                        :jar "bkrgraph-pdx-neptune-populator.jar"
                        :main-class "com.example"
                        :sync-pom true}}}}

**Comment by spmallette** [comment]
I see you've explicitly used `org.apache.commons/commons-configuration2 {:mvn/version "2.7"}}` - that's not in use until TinkerPop 3.5.0 - perhaps that is the problem. Maybe you need `commons-configuration`? 

https://github.com/apache/tinkerpop/blob/3.4.11/pom.xml#L596-L597

**Comment by danielmartincraig** [comment]
Fantastic, that solved it!!

**Comment by danielmartincraig** [comment]
You solved my issue!!  Thanks!

**Comment by danielmartincraig** [comment]
Hi Stephen, I want to write a vector of vertices to my tinkergraph all in
one shot - how can I do this? Can I represent vertices to be written as a
vector of anonymous traversals?

For background, I have written a Clojure library which I want to use to
batch tinkerpop objects before writing them to Neptune.  It implements the
following Java interface:

//----------------------------------------------
package com.example.neptunewriter;

import java.util.Date;

public interface NeptuneWriter {

    public void write(String item);

    public void close();
}
//----------------------------------------------

and I have implemented it like so:

;;----------------------------------------------
(ns com.example.my-neptune-writer
  (:require [clojurewerkz.ogre.core :as ogre :refer [traverse V addV values
match __ as has select by property into-seq! next!]]
                [clojure.core.async :as async :refer [>! <! >!! <!! go
go-loop chan buffer close! thread alt! alts! alts!! timeout]])
  (:import [com.example.neptunewriter NeptuneWriter]
               [org.apache.tinkerpop.gremlin.tinkergraph.structure
TinkerFactory]))

(defn batch [in max-time max-count]
  (let [lim-1 (dec max-count)
        out (chan)]
    (async/go-loop [buf []
                    t (async/timeout max-time)]
      (let [[v p] (async/alts! [in t])]
        (cond
          (= p t)  (do (async/>! out buf)
                       (recur [] (async/timeout max-time)))
          (nil? v) (do (if (seq buf)
                         (async/>! out buf))
                       (close! out))
          (== (inc (count buf)) max-count) (do (>! out (conj buf v))
                                               (recur [] (async/timeout
max-time)))
          :else    (recur (conj buf v) t))))
    out))

(def graph (TinkerFactory/createModern))

(def inChannel (chan))

(def batchedChannel (batch inChannel 500 100))

(go-loop [] (when-some [v (<! batchedChannel)]
              ;; TODO: write to the gremlin DB here
              (println (str v))
              (recur)))

(defn write [item]
  "all items passed to this method will eventually be written as part of a
batch"
  (>!! inChannel item))

(defn close []
  (do (println (str "Closing inChannel"))
       (close! inChannel)))

(defrecord NeptuneWriterImpl []
  NeptuneWriter
  (write [this item] (write item))
  (close [this] (close)))
;;----------------------------------------------

**Comment by spmallette** [comment]
> I want to write a vector of vertices to my tinkergraph all in one shot - how can I do this? Can I represent vertices to be written as a vector of anonymous traversals?

Maybe I don't completely follow what you want to do, but couldn't you just `inject()` a `List<Map>` (i.e. the vector) and do this with just Gremlin steps? This blog post shows how you can insert batches of vertices that way: https://stephen.genoprime.com/snippet/2020/03/28/snippet-7.html
