### ISSUE TITLE
What is the best way to pass a collection of relations?

### ISSUE THREAD

**Issue by Goldritter** [clojurewerkz/ogre#111]
Hi, 
I hope you can help me. 

To reduce my amount of code I want to make as much functions as reusable as possible. I have to create many queries, but the only difference is the type of relations which should be queried. To pass a collection of keywords (the relations) I rewrote the functions like inE, outE, bothE in a separate Namespace new and changed the input parameters from `(defn outE  [^GraphTraversal t & labels] ...)` to `(defn outE  [^GraphTraversal t & labels] ...)`, which works until it is "put" into the '__' Makro. 
In this case I get following Exception:

>  java.lang.ClassCastException: class clojure.lang.ArraySeq cannot be cast to class clojure.lang.Named (clojure.lang.ArraySeq and clojure.lang.Named are in unnamed module of loader 'app')

The reason is, that the '__' Makro uses its "own" inE, outE, ... functions (__inE, __outE, ....) and these expects again a var-args parameter for the relations. 

My question is now, if it is possible to rewrite functions like inE, outE, ... in a manner which allows it to pass the relations in a collection like `(inE [:is-a :exhibits])` or exists an other way to make queries more dynamic?

Here is an example how I wanted to make my queries more reusable. It is a function which receives the Graph g and the "labels" as  well the "relations" for the query which should find paths from the vertices with the given labels to all connected vertices with the given relations.

The usage should be like `(search-all-deep-relations ["Human" "Fish"] [:is-a :exhibits] :depth 4)`. In this case the query should find all vertices which have the relations/edges "is-a" or "exhibits" with a maximal depth of 4 with the starting vertices "Human" and "Fish".

```
(defn search-all-deep-relations-fn [g labels relations & {:keys [depth] :or {depth 3}}]
  (traverse g V
                 (has
                   :label (P/within
                            (if (coll? labels) labels [labels])))
                 (repeat
                   (__ (outE relations)
                            (otherV)))
                 (until (__ (outE relations) (count) (is 0) (or) (loops) (is depth)))
                 (path)
                 (by (__ (value-map :label :is-for)))
                 (into-vec!)))

(defn search-all-deep-relations [labels relations & {:keys [depth] :or {depth 3}}]
  (DB/execute-in-traversal-graph-session! #(search-all-deep-relations-fn %1 labels relations
                                                                         :depth depth)))
```

I hope I was able to express myself clearly and thank you in advance for your help.

With best regards
Marcus

**Comment by spmallette** [comment]
Hello, you wrote that you:

> changed the input parameters from `(defn outE [^GraphTraversal t & labels] ...)` to `(defn outE [^GraphTraversal t & labels] ...)`

but I don't see a difference between the two. Did you mistype something? Perhaps you could paste all the code for what you changed with `outE`?

**Comment by Goldritter** [comment]
Hi 
sorry, there is a typo in the last code snipped. I forget to remove the &. (Damn C&P error :( .)
Here is the complete code I "changed"

```
(ns gremlin.ogre-addons
  (:require [clojure.tools.logging :as LOG]
            [clojurewerkz.ogre.core :as OGRE]
            [clojurewerkz.ogre.util :as util])
  (:import (org.apache.tinkerpop.gremlin.process.traversal.dsl.graph GraphTraversal)))
;; Helper functions which are different/specialized implementations of Ogre functions mainly to use collections as passing parameter instead of var-args

(defn both
  [^GraphTraversal t labels]
  (let [label-array (util/keywords-to-str-array labels)]
    (.both t label-array)))

(defn outE
  [^GraphTraversal t labels]
  (let [label-array (util/keywords-to-str-array labels)]
    (.outE t label-array)))

(defn inE
  [^GraphTraversal t labels]
  (let [label-array (util/keywords-to-str-array labels)]
    (.inE t label-array)))

(defn bothE
  [^GraphTraversal t labels]
  (let [label-array (util/keywords-to-str-array labels)]
    (.bothE t label-array)))

(defn select
  [^GraphTraversal t arg1]
  (if (coll? arg1) (apply OGRE/select t arg1)
                   (OGRE/select t arg1)))
```

The Problem is more how var-args are transformed during usage. For example if I wrote `(inE :foo :bar)` it is transformed by `& labels` into a list or vector [:foo :bar] which can be  processed by `util/keywords-to-str-array`, but if I have to write it `(inE [:foo :bar])`, because I had to pass the relations as a collection, it is transformed to the vector [[:foo :bar]] and this causes an error in `util/keywords-to-str-array`.  And how the used Makros destructure the functions I cannot use `apply`. If I write `(apply inE [:foo :bar])`  I get an Exception.
And until now I have found no other way to use a collection as a parameter in `inE`, `outE`, ...
As I wrote above the code works fine but if a `__` is used it causes Exceptions, because the `__` forces to usage of `__inE`. 

Currently I use a rather crude workaround in which I define the query as a function in a string, then insert the desired parameters in the appropriate places of the string, read the string with `read-string` and then execute it with `eval`.

**Comment by spmallette** [comment]
i think i understand the problem better now - the calls to `__` don't use your custom implementations basically and there is no way to control that because it is driven by a macro.  i really don't know how to fix that. could you build your own special macro, like `__x` that just calls your overridden versions for anonymous traversals?  

```
(defmacro __x
  "Starts a custom anonymous traversal."
  [xs & body]
   `(-> (apply ~(symbol (str "gremlin.ogre-addons/__" (name (first xs)))) ~(vec (rest xs))) ~@body))
```

**Comment by Goldritter** [comment]
I had hoped not to have to do that. ;) It was a bit messy writing my own inE, outE, ... functions.

I will then see how I can best deal with the problem, if there is currently no easy-to-implement solution. 
I think I will currently do this via a separate string that represents the query and then parse and evaluate it.  

Thank you for your help.

**Comment by spmallette** [comment]
yeah - sorry - i'm good at gremlin/tinkerpop but not so great at elegant clojure.  :)

**Comment by Goldritter** [comment]
No Problem. Nobody is perfect ;) .
