### ISSUE TITLE
vertex and edge find-by-id methods behave differently when retrieving non-existent elements

### ISSUE THREAD

**Issue by Fitzoh** [clojurewerkz/ogre#24]
vertex/find-by-id is wrapped in a try catch, and returns nil if the vertex is not found.
edge/find-by-id is not wrapped, and a NoSuchElementException is thrown if an edge with that id is not found.

We should figure out the expected behavior is for this.

**Comment by sbelak** [comment]
For me ideally, not found would behave the same as if you'd do:

g.v(1).out().has("idontexist").both()...

that is return a Traversal over nothing, which is also closest to what would happen in clj-land if you go (->> filter map ...) where filter returns ().

**Comment by spmallette** [comment]
I don' think this issue is relevant anymore given the changes that have occurred on Ogre in the master branch to get it working with TinkerPop 3.1.2-incubating.
