### ISSUE TITLE
Complete Filter Steps

### ISSUE THREAD

**Issue by spmallette** [clojurewerkz/ogre#35]
Remaining steps to be added to `filter.clj` include:

* cyclicPath 
* inject 
* overloads for except/retain
* where

**Comment by sbelak** [comment]
It would be nice to add support for Compare/in (probably the best clj analogue is contains?).

**Comment by spmallette** [comment]
All steps are covered against 3.2.0-incubating, though we could do some nicer things with some of the filter options. I will open new issues as needed.
