### ISSUE TITLE
Support Match Step

### ISSUE THREAD

**Issue by spmallette** [clojurewerkz/ogre#37]
[Match](http://www.tinkerpop.com/docs/3.0.0-SNAPSHOT/#match-step) step is a new and powerful feature of TP3 that enables a more declarative style of graph pattern matching.  Add to `map.clj`.

**Comment by sbelak** [comment]
Have you given any thought how match should look? I'm thinking something along the lines of:
```
(q/query 
  ...
  (q/match :a
    :a (-> (q/out :created) (q/as :b))
    :b (q/has :name "lop")
    :b (-> (q/in :created) (q/as :c))
    :c (q/has :age 29))
  (q/select :a :c)
  ...)
 ```
(ie. modeled after core/cond->)

**Comment by spmallette** [comment]
That's pretty.  Watching this issue in TP3 for resolution might be good:

https://github.com/tinkerpop/tinkerpop3/issues/463

Discussion around the java/groovy representation of match

**Comment by sbelak** [comment]
That thread looks like tacit endorsement for having a language with macros.
It did however emphasize the importance of as, so this might be better:
```
(q/query 
  ...
  (q/match :a
    :a [(q/out :created) :as b]
    :b (q/has :name "lop")
    :b [(q/in :created) :as :c]
    :c (q/has :age 29))
  (q/select :a :c)
  ...)
```
This one is nice for short match statements, but I still prefer my original suggestion, as I feel it's closer to idiomatic Clojure, while the latter is more of a DSL (I still tried to follow look and feel of ns macro).

**Comment by spmallette** [comment]
Ultimately I implemented this pretty directly as:

```text
clojurewerkz.ogre.core=> (traverse g V (match
                    #_=>   (__ (as :a) (out :created) (as :b))
                    #_=>   (__ (as :b) (has :name "lop"))
                    #_=>   (__ (as :b) (in :created) (as :c))
                    #_=>   (__ (as :c) (has :age 29)))
                    #_=>   (select :a :c) (by :name)
                    #_=>   (into-seq!))
({"a" "marko", "c" "marko"} {"a" "josh", "c" "marko"} {"a" "peter", "c" "marko"})
```

If there can be improvements, let's open a fresh issue.
