### ISSUE TITLE
Provide Consistent Approach to Side Effects

### ISSUE THREAD

**Issue by spmallette** [clojurewerkz/ogre#42]
Ogre seemed to take a position of popping off side effects from a traversal by terminating the traversal with functions like `get-group-by!` or `get-group-count!`.  That's kinda neat - we just need to get consistent with an approach.

**Comment by sbelak** [comment]
The problem with this approach is that -- if I understand correctly -- it is incompatible with recursion, which is needed for things like calculating eigenvector centrality:
````
g.V().as('a').outE().inV().groupCount('m').jump('a',10000).cap('m')
```
The more I look at it, I don't really see the point of get-group-count! as it only shortcuts q/into-vec!

**Comment by spmallette** [comment]
I think that when I originally wrote this, we were in the midst of getting all of Ogre (and archimedes) reworked into TP3.  We were trying to preserve the existing spirit of Ogre, without changing too much - so rather than questioning these functions, I thought being consistent with them was a good idea.  Your argument is a good one though and I did think that `groupCount/By` needed to have their standard implementations present so as to allow for looping constructs to work.  Perhaps dropping support for those "helper" functions doesn't really hurt the "spirit" of Ogre all too much - as you say, they don't shortcut all too much.

**Comment by spmallette** [comment]
Those methods were ultimately dropped in the push to get Ogre working against TinkerPop 3.2.0-incubating.
