### ISSUE TITLE
Get Ogre Working against TP3 M7

### ISSUE THREAD

**Issue by spmallette** [clojurewerkz/ogre#62]
Created this branch to start bringing Ogre up to TP3 M7.  

https://github.com/clojurewerkz/ogre/tree/tp3m7

At this point there are still some test failures as it is currently committed to the branch.

**Comment by spmallette** [comment]
Fixed a few more test failures in relation to M7 in the `tp3m7` branch - these failures were related to `local` step - removed the old and more specific `local-range` and `local-limit` in the process.  A few more failing tests remain :grimacing:

**Comment by Fitzoh** [comment]
I've been doing a little bit of work on m9rc2 @ https://github.com/fitzoh/ogre/tree/tp3m9rc3

Maybe we should just have a tp3 branch and work towards the most recent tag?

**Comment by michaelklishin** [comment]
@Fitzoh I think tracking the most recent tag with Ogre's master is fine.

**Comment by spmallette** [comment]
Looks like with this most recent merge the `tp3m7` branch became part of `master`.  I'll kill that branch and do any future work on `master`.  official M9 should be out shortly - will get final remarks from vendors then release GA!  Ogre should be free of major breaking change at this point.

**Comment by spmallette** [comment]
The master branch is now working again TinkerPop 3.2.0-incubating - the most current release of TinkerPop.
