### ISSUE TITLE
Project still maintained?

### ISSUE THREAD

**Issue by parkan** [clojurewerkz/ogre#74]
We're starting to use ogre (v2.5.0 + archimedes to fill in missing pieces, which seems to work) and there's some concern whether the project is maintained. It looks like the last green CI build was [about 10 months ago](https://travis-ci.org/clojurewerkz/ogre/builds/58582496) and commits after that have been failing.

We're happy to jump in to help put out some fires, just want to get an idea of where things are at.

**Comment by parkan** [comment]
It looks like there's enough changes to cut a new release, possibly obviating the need to use archimedes alongside ogre -- can we tag e2240dced683ee074726000c57b66a2063471cc7 as v2.6 or fix up something more recent?

**Comment by spmallette** [comment]
@parkan It would be nice to see Ogre get fully stable again. some attempts have been made to get everything to a working state, but there are still some gaps.  the goal was to get all tests passing with Ogre as things are now without too much change and then refactor in a more controlled way to be more streamlined to TinkerPop 3.x.  As it stands, i believe we still have a bunch of broken tests and areas of incomplete coverage of the TinkerPop `GraphTraversal` API.  

Anyway, if you have ideas/time for how to help move this forward, i think that would be appreciated.  Unfortunately, I haven't had a ton of time to find my way back to Ogre - TinkerPop development itself has kept me a bit too busy.

**Comment by parkan** [comment]
Thanks for the update, @spmallette. It sounds like the amount of work needed probably exceeds our spare clock cycles a bit
