### ISSUE TITLE
TinkerGraph not found error

### ISSUE THREAD

**Issue by Robsteranium** [clojurewerkz/ogre#88]
When I try to require `clojurewerkz.ogre.core` an exception is raised because `org.apache.tinkerpop.gremlin.tinkergraph.structure.TinkerGraph` can't be found.

Perhaps the dependency `org.apache.tinkerpop/tinkergraph-gremlin` shouldn't be restricted to the test scope in project.clj?

Or is the expectation that users of the library should include this themselves? If so, perhaps the readme should be updated to suggest that?

**Comment by michaelklishin** [comment]
I agree. In the early days of the TinkerPop 3.x transition it made some sense to keep it as a development dependency because things changed every week.

@spmallette @Fitzoh WDYT?

**Comment by Fitzoh** [comment]
My initial inclination is to follow the convention that TP is using and have it be pulled in as a separate dependency, but I could go either way...
I've been out of the ecosystem for a while, so I think I'll defer to @spmallette

**Comment by spmallette** [comment]
It should be a test dependency only. Users should choose the graph database implementation they want to utilize and specify it directly. The README should probably be updated as suggested.

**Comment by Robsteranium** [comment]
Perhaps then the [no-arg implementation of `open-graph`](https://github.com/clojurewerkz/ogre/blob/master/src/clojure/clojurewerkz/ogre/core.clj#L26) ought to be removed (e.g. with that call moved into the tests)? As I understand it, clojure won't be able to read this namespace without `TinkerGraph` being on the classpath (even if another graph database is available).

**Comment by spmallette** [comment]
That makes sense to me. Not sure why I left that bit of code that way.

**Comment by michaelklishin** [comment]
@Robsteranium please submit a PR :)

**Comment by Robsteranium** [comment]
PR #89 has the changes I'm suggesting.

I couldn't seem to find any use of `(open-graph)` in the tests so I just put that call into the readme instead.
