### ISSUE TITLE
Version 3...-beta2 not in clojars

### ISSUE THREAD

**Issue by phreed** [clojurewerkz/ogre#90]
[clojurewerkz/ogre "3.0.0.0-beta2"]
The latest version is clojars is 3.0.0.0-beta1

**Comment by michaelklishin** [comment]
I think we should release `beta3` by now and publish it to Clojars. Will do in the next couple of days.

**Comment by phreed** [comment]
Sounds good.

**Comment by spmallette** [comment]
I've just created the tag for 3.0.0 - https://github.com/clojurewerkz/ogre/tree/v3.0.0 - let's close this one once @michaelklishin has published to clojars.

**Comment by spmallette** [comment]
Latest GA releases are in clojars now
