### ISSUE TITLE
3.3.0 release

### ISSUE THREAD

**Issue by shooit** [clojurewerkz/ogre#97]
Looking at master, an issue with `into-set!` has been fixed... would it be possible to get a release that incorporates this fix?

**Comment by spmallette** [comment]
i just about have Ogre working with 3.3.0. if @michaelklishin has the time I think a release could be ready in the next week.

**Comment by michaelklishin** [comment]
Yeah, should be doable before the end of the week.

**Comment by shooit** [comment]
Awesome. Many thanks.

**Comment by spmallette** [comment]
Just wanted to update that the tag for release is in place on 3.3.0.0: 

https://github.com/clojurewerkz/ogre/tree/v3.3.0.0

**Comment by michaelklishin** [comment]
[3.3.0.0 is up](https://clojars.org/clojurewerkz/ogre/versions/3.3.0.0) on Clojars.
